### ISSUE TITLE
Unable to send/edit message as Server Owner

### ISSUE THREAD

**Issue by itsgaryk** [AnotherCat/message-bot#22]
**Describe the bug**
The bot strictly only allows members with a role to send/edit messages. It should allow the Server Owner to use commands.

**To Reproduce**
1. Configure an admin role for Message Manager
2. Try to send/edit a message as Server Owner but without the role

**Expected behavior**
It should work as expected for the Server Owner regardless

**Comment by quirky-bluejay** [comment]
I did deliberately avoid the normal default setting on most bots of giving perms to people with the `ADMINISTRATOR` permission in a server.
I did this because there might be situations where a person who's got admin perms you might not want them being able to edit messages, and i wanted it to be completely based on role set permissions.
However the server owner bypassing the requirement will not have this problem, and it makes sense for the owner to be able to do this.
So I will change checks to reflect this.
I'll probably also add a warning when an owner uses a role restricted command without the role being set

**Comment by quirky-bluejay** [comment]
I've added a bypass from the check for the admin role if you're a server owner.
So there are two cases where this will cause a difference in behavior:

1. When the admin role is not set
2. When the admin role is set but the owner does not have that role.

In both cases the check will pass and the command will work.

**Comment by itsgaryk** [comment]
Is this live? If so it doesn't seem to work.

I removed the bot admin role, attempted to send a message and get the same error
> You need the management role to do that!
> Contact your server admin if you think you should be able to do this

**Comment by quirky-bluejay** [comment]
I just realized that yes, i did not reload the live instance of the bot sorry :facepalm: 
It should be working now
